import { z } from "zod";
import type { ResourceConfig } from "@/lib/crud";
import { zUuid } from "@/lib/crud";

const GENDER = ["MALE", "FEMALE", "OTHER"] as const;
const ADMISSION_TYPE = ["COUNSELING", "MANAGEMENT", "LATERAL_ENTRY", "SPORTS", "NRI"] as const;

const pct = z.number().min(0).max(100);

// ---------- Students (Module 3) ----------
export const studentResource: ResourceConfig = {
  table: "students",
  entity: "student",
  permissionView: "student.read",
  permissionWrite: "student.update",
  permissionCreate: "student.create",
  permissionUpdate: "student.update",
  permissionDelete: "student.delete",
  softDelete: true,
  searchable: ["register_number", "name", "email"],
  filterable: {
    department_id: "department_id",
    batch_id: "batch_id",
    section_id: "section_id",
    status: "status",
    gender: "gender",
    admission_type: "admission_type",
  },
  sortable: {
    registerNumber: "register_number",
    name: "name",
    cgpa: "current_cgpa",
    createdAt: "created_at",
  },
  defaultSort: "register_number ASC",
  columns: [
    { api: "registerNumber", db: "register_number", insertable: true, updatable: true },
    { api: "name", db: "name", insertable: true, updatable: true },
    { api: "gender", db: "gender", insertable: true, updatable: true },
    { api: "dateOfBirth", db: "date_of_birth", insertable: true, updatable: true },
    { api: "email", db: "email", insertable: true, updatable: true },
    { api: "mobile", db: "mobile", insertable: true, updatable: true },
    { api: "tenthPercentage", db: "tenth_percentage", insertable: true, updatable: true },
    { api: "twelfthPercentage", db: "twelfth_percentage", insertable: true, updatable: true },
    { api: "diplomaPercentage", db: "diploma_percentage", insertable: true, updatable: true },
    { api: "admissionType", db: "admission_type", insertable: true, updatable: true },
    { api: "cutoffMark", db: "cutoff_mark", insertable: true, updatable: true },
    { api: "departmentId", db: "department_id", insertable: true, updatable: true },
    { api: "batchId", db: "batch_id", insertable: true, updatable: true },
    { api: "sectionId", db: "section_id", insertable: true, updatable: true },
    { api: "regulationId", db: "regulation_id", insertable: true, updatable: true },
    { api: "currentCgpa", db: "current_cgpa", insertable: true, updatable: true },
    { api: "activeArrears", db: "active_arrears", insertable: true, updatable: true },
    { api: "historyArrears", db: "history_arrears", insertable: true, updatable: true },
    { api: "status", db: "status", insertable: true, updatable: true },
    { api: "createdAt", db: "created_at" },
  ],
  createSchema: z.object({
    registerNumber: z.string().min(1).max(40),
    name: z.string().min(1).max(160),
    gender: z.enum(GENDER).optional(),
    dateOfBirth: z.string().date().optional(),
    email: z.string().email().optional(),
    mobile: z.string().max(20).optional(),
    tenthPercentage: pct.optional(),
    twelfthPercentage: pct.optional(),
    diplomaPercentage: pct.optional(),
    admissionType: z.enum(ADMISSION_TYPE).optional(),
    cutoffMark: z.number().min(0).max(200).optional(),
    departmentId: zUuid.optional(),
    batchId: zUuid.optional(),
    sectionId: zUuid.optional(),
    regulationId: zUuid.optional(),
    currentCgpa: z.number().min(0).max(10).optional(),
    activeArrears: z.number().int().min(0).optional(),
    historyArrears: z.number().int().min(0).optional(),
  }),
  updateSchema: z
    .object({
      name: z.string().min(1).max(160),
      gender: z.enum(GENDER),
      dateOfBirth: z.string().date(),
      email: z.string().email(),
      mobile: z.string().max(20),
      tenthPercentage: pct,
      twelfthPercentage: pct,
      diplomaPercentage: pct,
      admissionType: z.enum(ADMISSION_TYPE),
      cutoffMark: z.number().min(0).max(200),
      departmentId: zUuid.nullable(),
      batchId: zUuid.nullable(),
      sectionId: zUuid.nullable(),
      regulationId: zUuid.nullable(),
      currentCgpa: z.number().min(0).max(10),
      activeArrears: z.number().int().min(0),
      historyArrears: z.number().int().min(0),
      status: z.enum(["ACTIVE", "ALUMNI", "DROPPED"]),
    })
    .partial(),
};

// ---------- Admissions (Module 4) ----------
export const admissionResource: ResourceConfig = {
  table: "admissions",
  entity: "admission",
  permissionView: "admission.crud",
  permissionWrite: "admission.crud",
  searchable: ["school_name", "district"],
  filterable: {
    admission_year: "admission_year",
    department_id: "department_id",
    district: "district",
    admission_type: "admission_type",
  },
  sortable: { admissionYear: "admission_year", district: "district" },
  defaultSort: "admission_year DESC",
  columns: [
    { api: "studentId", db: "student_id", insertable: true, updatable: true },
    { api: "departmentId", db: "department_id", insertable: true, updatable: true },
    { api: "cohortId", db: "cohort_id", insertable: true, updatable: true },
    { api: "admissionYear", db: "admission_year", insertable: true, updatable: true },
    { api: "admissionType", db: "admission_type", insertable: true, updatable: true },
    { api: "isManagementQuota", db: "is_management_quota", insertable: true, updatable: true },
    { api: "isCounselingQuota", db: "is_counseling_quota", insertable: true, updatable: true },
    { api: "isLateralEntry", db: "is_lateral_entry", insertable: true, updatable: true },
    { api: "cutoffMark", db: "cutoff_mark", insertable: true, updatable: true },
    { api: "schoolName", db: "school_name", insertable: true, updatable: true },
    { api: "district", db: "district", insertable: true, updatable: true },
    { api: "state", db: "state", insertable: true, updatable: true },
  ],
  createSchema: z.object({
    studentId: zUuid.optional(),
    departmentId: zUuid.optional(),
    cohortId: zUuid.optional(),
    admissionYear: z.number().int().min(1980).max(2100),
    admissionType: z.enum(ADMISSION_TYPE).optional(),
    isManagementQuota: z.boolean().optional(),
    isCounselingQuota: z.boolean().optional(),
    isLateralEntry: z.boolean().optional(),
    cutoffMark: z.number().min(0).max(200).optional(),
    schoolName: z.string().max(200).optional(),
    district: z.string().max(120).optional(),
    state: z.string().max(120).optional(),
  }),
  updateSchema: z
    .object({
      departmentId: zUuid.nullable(),
      cohortId: zUuid.nullable(),
      admissionYear: z.number().int().min(1980).max(2100),
      admissionType: z.enum(ADMISSION_TYPE),
      isManagementQuota: z.boolean(),
      isCounselingQuota: z.boolean(),
      isLateralEntry: z.boolean(),
      cutoffMark: z.number().min(0).max(200),
      schoolName: z.string().max(200),
      district: z.string().max(120),
      state: z.string().max(120),
    })
    .partial(),
};
